
on:
  push:
    branches: [ development ]
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> novaxr-dev
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: development
          target_branch: novaxr-dev
          github_token: ${{ github.token }      
          
